---
title: "in-class_3"
author: "Sash"
date: "2024-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#for loop
for (number in 1:10){
  squared_number <- number^2
  print(paste("Square of the nunber:", squared_number))
}
```
```{r}
#while loop
counter <- 1

while (counter <= 17){
  print(paste("Current counter number:", counter))
  counter <- counter + 1
}
```
```{r}
#if-else statements
number <- 0

if (number > 0){
  print(paste("Number", number, "is positive"))
} else if (number < 0 ){
  print(paste("Number", number, "is negative"))
} else {
  print(paste("Number", number, "is zero"))
}

#a list
list_numbers <- c(5,-4,0,9,-18)

for (number in list_numbers) {
  if (number > 0) {
    print(paste("Number", number, "is positive"))
  } else if (number < 0) {
    print(paste("Number", number, "is negative"))
  } else {
    print(paste("Number", number, "is zero"))
  }
}

#function
number_looper <- function(list){
  for (number in list) {
    if (number > 0) {
      print(paste("Number", number, "is positive"))
    } else if (number < 0) {
      print(paste("Number", number, "is negative"))
    } else {
      print(paste("Number", number, "is zero"))
    }
  }
}

number_looper(list_numbers)

```

